### ISSUE TITLE
docker build失败

### ISSUE THREAD

**Issue by nKsnC** [lordfriend/Albireo#165]
![image](https://user-images.githubusercontent.com/47666274/95014129-6593ec00-0677-11eb-97d8-9c27c6003261.png)

```
RUN /etc/init.d/postgresql start && sleep 10 && psql -U postgres -d postgres -c "alter user postgres with password '123456';"
RUN /etc/init.d/postgresql start && sleep 10 && createdb -O postgres albireo

RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade pip
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt --ignore-installed six
```

~~以上是我改变之后，成功build。~~ 
~~（10/04更新：后续还是出现了问题，回过头来看还是有问题）~~
10/04更新：问题解决，成功build。

---

~~第一处更改使用RUN exec的格式（https://www.jianshu.com/p/f0a0f6a43907 ），如果用shell格式，docker会在命令前加/bin/sh -c，导致不能正确执行，构建失败。（报错`psql: FATAL:  the database system is starting up`）~~

第二处，`pip -r requirements.txt`  报错`error in Twisted setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.`

看这个https://github.com/giampaolo/psutil/issues/1268 ，大概是因为pip 版本太低导致的。进入docker看pip只有1.5.4，最新为20.2.3.所以更新之后就可以了。

不过这里还有一个问题，
`DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.`

pip 21不会支持python2，之后更新pip会不会出问题，还不知道。

第三处，`--ignore-installed six`   
报错`ERROR: Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`  
参考https://stackoverflow.com/questions/50954182/python-cannot-uninstall-six-while-pip-install-tld  
所以添加这个。

改完后就能成功build。

**Comment by nKsnC** [comment]
关于第一处，我说错了，之后我运行程序时会有
`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"`

这个报错，然后我找到了 https://stackoverflow.com/questions/43657126/flask-alchemy-psycopg2-operationalerror-fatal-password-authentication-fai 和 https://askubuntu.com/questions/413585/postgres-password-authentication-fails

然后回过头看构建，果然`psql -U postgres -d postgres -c "alter user postgres with password '123456';" `  
这一句没有运行，然后分开运行发现并不是RUN格式的问题。

---
以下是这个问题的后续的相关信息。  
如果 `RUN /etc/init.d/postgresql start && psql -U postgres -d postgres -c "alter user postgres with password '123456';"`  
这样build，会报错 `psql: FATAL: the database system is starting up`  

而如果
```
RUN /etc/init.d/postgresql start 
RUN psql -U postgres -d postgres -c "alter user postgres with password '123456';"
```
这样build，则会报错
```psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?```

迷惑的地方来了，我build到这，然后去容器里运行这两行却能成功运行

这该怎么解决？

**Comment by nKsnC** [comment]
问题大概出现在这里  
![image](https://user-images.githubusercontent.com/47666274/95011734-7b001a80-0665-11eb-9bed-9d821205faf2.png)

并没有成功启动postgresql

**Comment by nKsnC** [comment]
参考 https://github.com/helvalius/nominatim-docker/issues/15#issuecomment-212542355

我将那行改为了  
`RUN /etc/init.d/postgresql start && sleep 10 && psql -U postgres -d postgres -c "alter user postgres with password '123456';" && createdb -O postgres albireo`

成功build了，因为postgresql没有真正启动就去运行下一行了，这是postgresql的锅

**Comment by lordfriend** [comment]
哦，这个repo的Dockerfile 我从来都没用过。之后我看一下现在用的dockerfile吧

**Comment by nKsnC** [comment]
@lordfriend 好的，十分感谢。虽然build成功了，但程序运行还是会有这个错误  
`OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"`

唉，我不是应该再开个issue？

（抱歉，刚刚不小心关闭issue了）

**Comment by lordfriend** [comment]
这个dockerfile是为了直接docker做开发而加的（别人加的）。但我平时并没有用docker开发这个，而是直接在系统里装了所有依赖。
运行的实例的dockerfile是每个container只跑一个程序，postgres，deluge都是用的官方的image。用docker-compose来管理的

**Comment by nKsnC** [comment]
@lordfriend 哦，这样啊。不过目前我也成功build了，这个环节也没其他问题了。之前提到的那个问题我再看看，如果有必要我会再提issue的。

**Comment by nKsnC** [comment]
@lordfriend 额，还是需要看看，可能有些细节配置不一样吧，可以的话，方便传一份吗？

**Comment by nKsnC** [comment]
这个dockerfile真的很烂。我很好奇有人真的靠这个dockerfile 成功搭建环境了吗  

`OperationalError: (psycopg2.OperationalError) FATAL: password authentication failed for user "postgres" FATAL: password authentication failed for user "postgres"`  
这个报错，就是密码验证不对，dockfile那行并没有更改密码。具体参考 https://www.jianshu.com/p/16683b09e9f0  
所以应该是  
`psql -U postgres -d postgres -c "alter role postgres with password '123456';"`

---
然后接下来，又报错|д` )   

`AttributeError: 'module' object has no attribute 'pbkdf2_hmac'`
参考：https://github.com/pennlabs/labs-api-server/issues/66

> Reason: server has Python 2.7.6, pbkdf2_hmac was introduced in 2.7.8

而Ubuntu安装是python 2.7.6还不能”更新“。当然，要更新也有办法https://askubuntu.com/questions/725171/update-python-2-7-to-latest-version-of-2-x

真的好麻烦，我真的不想再看这个了。你们有已经验证能运行就commit上来吧。

看了这么多，我觉得都能自己搭这个环境了= =

**Comment by lordfriend** [comment]
明天把在用的dockerfile发一下吧，现在登不上服务器。之后我看看把这个dockerfile删掉好了。好像不止一个人掉这个坑了

**Comment by lordfriend** [comment]
create folder structure like below:

### create a project (can be any name) folder for all files

`/project/albireo/Dockerfile`

`/project/albireo/Albireo`  // this is your git repo directory

`/project/config/albireo/config.yml` // this is the config file copied from `/project/albireo/Albireo/config/config.sample.yml`

`/project/config/albireo/sentry.yml` // this is optional. you may not need this

`/project/config/alembic.ini` // this is for upgrading database if you want to keep update with the official branch. copy a sample file from `/project/albireo/Albireo/alembic.ini.example`

`/project/config/deluge` // for deluge config file

`/project/data/downloads` // temp folder for deluge downloads locations. 

`/project/docker-compose.yml` the docker-compose file for management all container. see below

### Create folders for video and other data files

grant permission for you `docker` usergroup

`/docker_data/albireo/data`
`/docker_data/postgres`

Dockerfile, `/project/albireo/Dockerfile`
```
FROM ubuntu:16.04

RUN apt update && apt install -y wget tar python python-pip curl libcurl4-openssl-dev locales

RUN mkdir -p /usr/app

WORKDIR /usr/app

RUN apt install -y ffmpeg postgresql-client python-dev libyaml-dev python-psycopg2 openssl python-imaging 

RUN apt install -y build-essential libssl-dev libffi-dev deluged nodejs

COPY Albireo/requirements.txt .

RUN pip install -r requirements.txt

RUN locale-gen en_US.UTF-8 

ENV LANG en_US.UTF-8

RUN useradd -u 1000 --create-home user

RUN chown user:user -R /usr/app 

RUN mkdir -p /data

RUN chown user:user -R /data

USER user

COPY Albireo/ /usr/app/
```

docker-compose.yml
```
version: "2"
services:
  postgres:
    image: postgres
    ports: 
      - 127.0.0.1:5433:5432
#    environment:
#      POSTGRES_USER: "${POSTGRES_USER}"
#      POSTGRES_PASSWORD: "${POSTGRES_USER}"
    volumes:
      - /docker_data/postgres/:/var/lib/postgresql/data:rw
    restart: always
  albireo-web:
    build:
      context: albireo
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - 127.0.0.1:30001:5000
    volumes:
      - ./config/albireo/config.yml:/usr/app/config/config.yml:ro
      - ./config/albireo/sentry.yml:/usr/app/config/sentry.yml:ro
      - ./config/albireo/alembic.ini:/usr/app/alembic.ini:ro
      - /docker_data/albireo/data:/data/Albireo:rw
    command: "twistd -n --pidfile= web --port 5000 --wsgi appd.app"
  albireo-schedule:
    build:
      context: albireo
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./config/albireo/config.yml:/usr/app/config/config.yml:ro
      - ./config/albireo/sentry.yml:/usr/app/config/sentry.yml:ro
      - ./config/albireo/alembic.ini:/usr/app/alembic.ini:ro
      - /docker_data/albireo/data:/data/Albireo:rw
    command: "/usr/bin/python Scheduler.py"
  deluge:
    image: linuxserver/deluge
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 30002:8112
      - 30003:30003/tcp
      - 30003:30003/udp
    volumes:
      - ./data/downloads:/downloads
      - ./config/deluge:/config
      - /docker_data/albireo/data:/data/Albireo:rw
    restart: always
```


Note that you need to modify the /project/config/albireo/config.yml to make sure all default variable is updated for your needs.
You also need to read the official documents of the postgres image and deluge image to know how to configure it like set database user and password
